name: verify-binary-architecture
on: push
# on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build-release:
    name: build-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          # - x86_64-unknown-linux-musl
          # - aarch64-unknown-linux-musl
          # - x86_64-apple-darwin
          # - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
        toolchain: [stable]
        include:
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-musl
          #   use-cross: true
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-musl
          #   use-cross: true
          # # macos>=14 runs exclusively on aarch64 and will thus fail to execute properly for x64
          # - os: macos-13
          #   target: x86_64-apple-darwin
          #   use-cross: false
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          #   use-cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}

      - name: Handle Rust dependencies caching
        uses: Swatinem/rust-cache@v2
        with:
          key: v1-${{ matrix.target }}

      - name: Build release binary
        uses: clechasseur/rs-cargo@v2
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}

      - name: Verify binary architecture
        shell: bash
        run: |
          set -xeuo pipefail

          BINARY_PATH="target/${{ matrix.target }}/release/gleam"
          if [[ "${{ matrix.target }}" == *"-windows-"* ]]; then
            BINARY_PATH="${BINARY_PATH}.exe"
          fi

          case "${{ matrix.target }}" in
            "x86_64"*) TARGET_ARCHITECTURE="x86_64" ;;
            "aarch64"*) TARGET_ARCHITECTURE="aarch64" ;;
            *) echo "Unknown architecture for target '${{ matrix.target }}'"; exit 1 ;;
          esac

          case "${{ matrix.target }}" in
            *"-darwin"*)
              FILE_OUTPUT=$(file "${BINARY_PATH}")
              echo "DEBUG: Full file output: ${FILE_OUTPUT}"
              FILE_CONTENT=${FILE_OUTPUT#"${BINARY_PATH}: "}
              echo "DEBUG: After removing prefix: ${FILE_CONTENT}"
              BINARY_ARCHITECTURE=$(echo "$FILE_CONTENT" | grep -o "x86_64\|arm64" || echo "")
              echo "DEBUG: Found architecture: ${BINARY_ARCHITECTURE}"
              case "${TARGET_ARCHITECTURE}" in
                "x86_64") EXPECTED_BINARY_ARCHITECTURE="x86_64" ;;
                "aarch64") EXPECTED_BINARY_ARCHITECTURE="arm64" ;;
                *) echo "Unknown Darwin architecture: ${TARGET_ARCHITECTURE}"; exit 1 ;;
              esac
              ;;
            *"-linux-"*)
              FILE_OUTPUT=$(file "${BINARY_PATH}")
              echo "DEBUG: Full file output: ${FILE_OUTPUT}"
              FILE_CONTENT=${FILE_OUTPUT#"${BINARY_PATH}: "}
              echo "DEBUG: After removing prefix: ${FILE_CONTENT}"
              BINARY_ARCHITECTURE=$(echo "$FILE_CONTENT" | grep -o "x86-64\|aarch64" || echo "")
              echo "DEBUG: Found architecture: ${BINARY_ARCHITECTURE}"
              case "${TARGET_ARCHITECTURE}" in
                "x86_64") EXPECTED_BINARY_ARCHITECTURE="x86-64" ;;
                "aarch64") EXPECTED_BINARY_ARCHITECTURE="aarch64" ;;
                *) echo "Unknown Linux architecture: ${TARGET_ARCHITECTURE}"; exit 1 ;;
              esac
              ;;
            *"-windows-"*)
              echo "DEBUG: Checking Windows binary: ${BINARY_PATH}"

              echo "=== Method 1: dumpbin ==="
              DUMPBIN_OUT=$(powershell -Command "if (Get-Command dumpbin -ErrorAction SilentlyContinue) { dumpbin /headers '${BINARY_PATH}' } else { Write-Output 'dumpbin not found' }" || echo "dumpbin check failed")
              echo "Dumpbin output: ${DUMPBIN_OUT}"

              echo "=== Method 2: Get-Item ==="
              GETITEM_OUT=$(powershell -Command "Get-Item '${BINARY_PATH}' | Format-List" || echo "Get-Item check failed")
              echo "Get-Item output: ${GETITEM_OUT}"

              echo "=== Method 3: PE Header check ==="
              PE_OUT=$(powershell -Command "\$bytes = [System.IO.File]::ReadAllBytes('${BINARY_PATH}'); Write-Output 'Magic number:'; \$bytes[0,1]; if (\$bytes[0,1] -eq 77,90) { Write-Output 'Valid PE file' }" || echo "PE header check failed")
              echo "PE Header output: ${PE_OUT}"

              echo "=== Method 4: Get-Command ==="
              GETCMD_OUT=$(powershell -Command "Get-Command '${BINARY_PATH}' | Format-List" || echo "Get-Command check failed")
              echo "Get-Command output: ${GETCMD_OUT}"

              echo "=== Method 5: PE Detail check ==="
              PEDETAIL_OUT=$(powershell -Command "try { \$bytes = [System.IO.File]::ReadAllBytes('${BINARY_PATH}'); \$peOffset = [System.BitConverter]::ToInt32(\$bytes[0x3c..0x3f], 0); Write-Output ('PE Header offset: 0x{0:X}' -f \$peOffset); Write-Output 'Machine type:'; \$bytes[\$peOffset+4..\$peOffset+5] } catch { Write-Output 'Error reading PE header' }" || echo "PE detail check failed")
              echo "PE Detail output: ${PEDETAIL_OUT}"

              echo "DEBUG: All outputs collected, continuing with analysis"
              ;;
            # *"-windows-"*)
            #   echo "DEBUG: Checking Windows binary: ${BINARY_PATH}"
            #   PS_OUTPUT=$(powershell -Command "[System.Reflection.AssemblyName]::GetAssemblyName('${BINARY_PATH}').ProcessorArchitecture")
            #   echo "DEBUG: PowerShell output: ${PS_OUTPUT}"
            #   BINARY_ARCHITECTURE="${PS_OUTPUT}"
            #   echo "DEBUG: Windows binary architecture output: ${BINARY_ARCHITECTURE}"
            #   case "${TARGET_ARCHITECTURE}" in
            #     "x86_64") EXPECTED_BINARY_ARCHITECTURE="X64" ;;
            #     "aarch64") EXPECTED_BINARY_ARCHITECTURE="Arm64" ;;
            #     *) echo "Unknown Windows architecture: ${TARGET_ARCHITECTURE}"; exit 1 ;;
            #   esac
            #   ;;
            *)
              echo "Unknown OS in target: '${{ matrix.target }}'"
              exit 1
              ;;
          esac

          if [[ -z "${EXPECTED_BINARY_ARCHITECTURE}" ]]; then
            echo "Unknown architecture '${TARGET_ARCHITECTURE}' for target '${{ matrix.target }}'"
            exit 1
          fi

          if [[ "${BINARY_ARCHITECTURE}" != "${EXPECTED_BINARY_ARCHITECTURE}" ]]; then
            echo "Architecture mismatch for '${{ matrix.target }}'"
            echo "Expected: '${EXPECTED_BINARY_ARCHITECTURE}'"
            echo "Got: '${BINARY_ARCHITECTURE}'"
            exit 1
          fi
